[logger]
level = "error"

[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[server]
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
